"""add indexes for reminders

Revision ID: 4a3d7909f328
Revises: c88facae7745
Create Date: 2026-05-13 17:04:37.619548

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a3d7909f328"
down_revision: Union[str, Sequence[str], None] = "c88facae7745"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_spisok_del_user_done_cover")
    op.execute("DROP INDEX IF EXISTS ix_spisok_del_user_id_is_done")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     op.f("ix_spisok_del_user_done_cover"),
    #     table_name="spisok_del",
    #     postgresql_include=["title", "deadline"],
    # )
    # op.drop_index(op.f("ix_spisok_del_user_id_is_done"), table_name="spisok_del")
    op.create_index(
        "ix_spisok_del_done_deadline",
        "spisok_del",
        ["is_done", "deadline"],
        unique=False,
    )
    op.create_index(
        "ix_spisok_del_reminder_pending",
        "spisok_del",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text("reminder_sent = false AND is_done = false AND user_id IS NOT NULL"),
    )
    op.create_index("ix_spisok_del_reminder_sent", "spisok_del", ["reminder_sent"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_spisok_del_reminder_sent", table_name="spisok_del")
    op.drop_index(
        "ix_spisok_del_reminder_pending",
        table_name="spisok_del",
        postgresql_where=sa.text("reminder_sent = false AND is_done = false AND user_id IS NOT NULL"),
    )
    op.drop_index("ix_spisok_del_done_deadline", table_name="spisok_del")
    op.create_index(
        op.f("ix_spisok_del_user_id_is_done"),
        "spisok_del",
        ["user_id", "is_done"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spisok_del_user_done_cover"),
        "spisok_del",
        ["user_id", "is_done"],
        unique=False,
        postgresql_include=["title", "deadline"],
    )
    # ### end Alembic commands ###
