"""replace_is_done_with_status_indexes

Revision ID: 4c9b58a062c6
Revises: add_task_status_kanban
Create Date: 2026-06-18 14:39:13.872709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4c9b58a062c6"
down_revision: Union[str, Sequence[str], None] = "add_task_status_kanban"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    # op.drop_index(op.f("ix_audit_log_changed_at"), table_name="audit_log")
    # op.drop_index(op.f("ix_audit_log_entity"), table_name="audit_log")
    # op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    # # op.drop_index(
    # #     op.f("ix_comments_not_deleted"),
    # #     table_name="comments",
    # #     postgresql_where="(deleted_at IS NULL)",
    # )
    # op.drop_index(
    #     op.f("ix_notification_settings_created_at"), table_name="notification_settings"
    # )
    # op.execute("DROP INDEX IF EXISTS ix_notification_settings_created_at")
    # op.drop_index(
    #     op.f("ix_notification_settings_notify_group_assigned"),
    #     table_name="notification_settings",
    # )
    # op.drop_index(
    #     op.f("ix_notification_settings_updated_at"), table_name="notification_settings"
    # )
    op.drop_index(op.f("ix_spisok_del_is_done"), table_name="spisok_del")
    op.drop_index(op.f("ix_spisok_del_priority"), table_name="spisok_del")
    op.drop_index(op.f("ix_spisok_del_priority_done"), table_name="spisok_del")
    op.drop_index(op.f("ix_spisok_del_project_id"), table_name="spisok_del")
    op.drop_index(op.f("ix_spisok_del_project_status"), table_name="spisok_del")
    op.drop_index(
        op.f("ix_spisok_del_title_gin"), table_name="spisok_del", postgresql_using="gin"
    )
    op.drop_index(
        op.f("ix_spisok_del_title_trgm"),
        table_name="spisok_del",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_spisok_del_user_status"), table_name="spisok_del")
    op.drop_index(op.f("ix_spisok_del_author_done"), table_name="spisok_del")
    op.create_index(
        "ix_spisok_del_author_done", "spisok_del", ["author_id", "status"], unique=False
    )
    op.drop_index(op.f("ix_spisok_del_done_deadline"), table_name="spisok_del")
    op.create_index(
        "ix_spisok_del_done_deadline",
        "spisok_del",
        ["status", "deadline"],
        unique=False,
    )
    op.drop_index(op.f("ix_spisok_del_group_done"), table_name="spisok_del")
    op.create_index(
        "ix_spisok_del_group_done", "spisok_del", ["group_id", "status"], unique=False
    )
    op.drop_index(op.f("ix_spisok_del_user_done"), table_name="spisok_del")
    op.create_index(
        "ix_spisok_del_user_done", "spisok_del", ["user_id", "status"], unique=False
    )
    op.drop_column("spisok_del", "is_done")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spisok_del",
        sa.Column("is_done", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_spisok_del_user_done", table_name="spisok_del")
    op.create_index(
        op.f("ix_spisok_del_user_done"),
        "spisok_del",
        ["user_id", "is_done"],
        unique=False,
    )
    op.drop_index("ix_spisok_del_group_done", table_name="spisok_del")
    op.create_index(
        op.f("ix_spisok_del_group_done"),
        "spisok_del",
        ["group_id", "is_done"],
        unique=False,
    )
    op.drop_index("ix_spisok_del_done_deadline", table_name="spisok_del")
    op.create_index(
        op.f("ix_spisok_del_done_deadline"),
        "spisok_del",
        ["is_done", "deadline"],
        unique=False,
    )
    op.drop_index("ix_spisok_del_author_done", table_name="spisok_del")
    op.create_index(
        op.f("ix_spisok_del_author_done"),
        "spisok_del",
        ["author_id", "is_done"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spisok_del_user_status"),
        "spisok_del",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spisok_del_title_trgm"),
        "spisok_del",
        ["title"],
        unique=False,
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_spisok_del_title_gin"),
        "spisok_del",
        [
            sa.literal_column(
                "to_tsvector('russian'::regconfig, COALESCE(title, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_spisok_del_project_status"),
        "spisok_del",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spisok_del_project_id"), "spisok_del", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_spisok_del_priority_done"),
        "spisok_del",
        ["priority", "is_done"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spisok_del_priority"), "spisok_del", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_spisok_del_is_done"), "spisok_del", ["is_done"], unique=False
    )
    # op.create_index(
    #     op.f("ix_notification_settings_updated_at"),
    #     "notification_settings",
    #     ["updated_at"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_notification_settings_notify_group_assigned"),
    #     "notification_settings",
    #     ["notify_group_assigned"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_notification_settings_created_at"),
    #     "notification_settings",
    #     ["created_at"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_comments_not_deleted"),
    #     "comments",
    #     ["task_id"],
    #     unique=False,
    #     postgresql_where="(deleted_at IS NULL)",
    # )
    # op.create_index(
    #     op.f("ix_audit_log_user_id"),
    #     "audit_log",
    #     ["user_id", "changed_at"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_audit_log_entity"),
    #     "audit_log",
    #     ["entity_type", "entity_id", "changed_at"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_audit_log_changed_at"), "audit_log", ["changed_at"], unique=False
    # )
    # op.create_index(
    #     op.f("ix_audit_log_action"), "audit_log", ["action", "changed_at"], unique=False
    # )
    # ### end Alembic commands ###
