"""add_notification_settings_and_indexes

Revision ID: 7c53145af9bd
Revises: 4a3d7909f328
Create Date: 2026-05-13 19:54:36.232165

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c53145af9bd"
down_revision: Union[str, Sequence[str], None] = "4a3d7909f328"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notify_deadline_24h", sa.Boolean(), nullable=False),
        sa.Column("notify_deadline_1h", sa.Boolean(), nullable=False),
        sa.Column("notify_overdue", sa.Boolean(), nullable=False),
        sa.Column("weekly_report_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_task_assigned", sa.Boolean(), nullable=False),
        sa.Column("notify_task_updated", sa.Boolean(), nullable=False),
        sa.Column("notify_comment", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "ix_notification_settings_any_enabled",
        "notification_settings",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text(
            "notify_deadline_24h = true "
            "OR notify_deadline_1h = true "
            "OR notify_overdue = true "
            "OR weekly_report_enabled = true"
        ),
    )
    op.create_index(
        "ix_notification_settings_notify_deadline_1h",
        "notification_settings",
        ["notify_deadline_1h"],
        unique=False,
    )
    op.create_index(
        "ix_notification_settings_notify_deadline_24h",
        "notification_settings",
        ["notify_deadline_24h"],
        unique=False,
    )
    op.create_index(
        "ix_notification_settings_notify_overdue",
        "notification_settings",
        ["notify_overdue"],
        unique=False,
    )
    op.create_index(
        "ix_notification_settings_user_id",
        "notification_settings",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_settings_user_weekly",
        "notification_settings",
        ["user_id", "weekly_report_enabled"],
        unique=False,
    )
    op.create_index(
        "ix_notification_settings_weekly_active",
        "notification_settings",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("weekly_report_enabled = true"),
    )
    op.create_index(
        "ix_notification_settings_weekly_report_enabled",
        "notification_settings",
        ["weekly_report_enabled"],
        unique=False,
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["spisok_del.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_telegram_active", "users", ["telegram_id", "is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_telegram_active", table_name="users")
    op.drop_table("notification_logs")
    op.drop_index(
        "ix_notification_settings_weekly_report_enabled",
        table_name="notification_settings",
    )
    op.drop_index(
        "ix_notification_settings_weekly_active",
        table_name="notification_settings",
        postgresql_where=sa.text("weekly_report_enabled = true"),
    )
    op.drop_index("ix_notification_settings_user_weekly", table_name="notification_settings")
    op.drop_index("ix_notification_settings_user_id", table_name="notification_settings")
    op.drop_index("ix_notification_settings_notify_overdue", table_name="notification_settings")
    op.drop_index(
        "ix_notification_settings_notify_deadline_24h",
        table_name="notification_settings",
    )
    op.drop_index(
        "ix_notification_settings_notify_deadline_1h",
        table_name="notification_settings",
    )
    op.drop_index(
        "ix_notification_settings_any_enabled",
        table_name="notification_settings",
        postgresql_where=sa.text(
            "notify_deadline_24h = true "
            "OR notify_deadline_1h = true "
            "OR notify_overdue = true "
            "OR weekly_report_enabled = true"
        ),
    )
    op.drop_table("notification_settings")
    # ### end Alembic commands ###
