"""fix deadline timezone-2

Revision ID: 7e622372c1c3
Revises: 91e55edc856c
Create Date: 2026-03-20 14:47:08.467032

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7e622372c1c3"
down_revision: Union[str, Sequence[str], None] = "91e55edc856c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
