"""add indexes and improve timestamps on spisok_del

Revision ID: f1a59d8d63c6
Revises: 600980d30e14
Create Date: 2026-05-11 16:34:54.349049

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a59d8d63c6"
down_revision: Union[str, Sequence[str], None] = "600980d30e14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_spisok_del_author_done",
        "spisok_del",
        ["author_id", "is_done"],
        unique=False,
    )
    op.create_index(
        "ix_spisok_del_author_id", "spisok_del", ["author_id"], unique=False
    )
    op.create_index("ix_spisok_del_deadline", "spisok_del", ["deadline"], unique=False)
    op.create_index(
        "ix_spisok_del_deadline_user",
        "spisok_del",
        ["deadline", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_spisok_del_group_done", "spisok_del", ["group_id", "is_done"], unique=False
    )
    op.create_index("ix_spisok_del_group_id", "spisok_del", ["group_id"], unique=False)
    op.create_index("ix_spisok_del_is_done", "spisok_del", ["is_done"], unique=False)
    op.create_index(
        "ix_spisok_del_user_done", "spisok_del", ["user_id", "is_done"], unique=False
    )
    op.create_index("ix_spisok_del_user_id", "spisok_del", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_spisok_del_user_id", table_name="spisok_del")
    op.drop_index("ix_spisok_del_user_done", table_name="spisok_del")
    op.drop_index("ix_spisok_del_is_done", table_name="spisok_del")
    op.drop_index("ix_spisok_del_group_id", table_name="spisok_del")
    op.drop_index("ix_spisok_del_group_done", table_name="spisok_del")
    op.drop_index("ix_spisok_del_deadline_user", table_name="spisok_del")
    op.drop_index("ix_spisok_del_deadline", table_name="spisok_del")
    op.drop_index("ix_spisok_del_author_id", table_name="spisok_del")
    op.drop_index("ix_spisok_del_author_done", table_name="spisok_del")
    # ### end Alembic commands ###
