"""add comment

Revision ID: f5cf6193b56d
Revises: 659c5fd2d985
Create Date: 2026-03-20 13:16:51.171165

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f5cf6193b56d"
down_revision: Union[str, Sequence[str], None] = "659c5fd2d985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
